### ISSUE TITLE
Player is teleported to wrong place, when turned

### ISSUE THREAD

**Issue by CarverGoofballJunior** [Rnen/SCPSL-SCP008#15]
Hi, there is problem with turning into 008. When player gets turned he either teleports to SCP-049 spawn (if he didn't die before) or to previous death place. For example I died as class D in Pocket Dimension, respawned as MTF, was infected and turned into 008 and after turning I was teleported to Pocket Dimension, to exact spot where I died. Could you fix this please?

**Comment by Rnen** [comment]
Noticed this myself :ok_hand: 
Unsure if this is due to SMod issues or not, trying to make a work-around fix.
